### PR TITLE
FINAL CAPSTONE - Sailvation App Frontend

### PR DESCRIPTION
**Pull request by hamid-murambiwa**
Project Requirements:
- Setup react and redux
- Create a home page in which users can see a list of cruises.
- Create a navigation panel
- Create a reservation page so that a user can reserve a cruise.
- Create a reservation index so that a user can see the list of all their reservations.
- Create a form for adding new items.
- Create a cancel page so that when the user clicks the "Cancel item" link in the navigation panel they can see a list of all items with title and "Cancel" button.
- Add authentication so that a user can login to a website

### CODE REVIEW

**Review by MuriloRoque — CHANGES_REQUESTED** [review]
Hi @hamid-murambiwa, @luftedar, @karelvanoordt, @Busiwa24,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes

- [ ] Add tests to you front-end app.
- [ ] There are a few commented lines of code you are not using anymore, I suggest deleting them.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by karelvanoordt** [comment]
Hi @MuriloRoque !

Thanks for your review and for the insights! I just have one question.
Do we have to create another PR for the tests implementation (and another branch, of course)?
We want to avoid any kind of conflicts in this branch.

Cheers!

**Comment by MuriloRoque** [comment]
Hey @karelvanoordt, the right thing to to is to create a feature branch and then a PR from that branch to your development branch. Then after merging that PR, your changes would be here in this PR and you can send it again for review.

**Comment by MuriloRoque** [comment]
But you can just create the new feature branch from development branch, this would avoid any merge conflicts.

**Review by MuriloRoque — APPROVED** [review]
H @hamid-murambiwa, @karelvanoordt, @luftedar, @Busiwa24,

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
